### ISSUE TITLE
Feedback for “Levels”

### ISSUE THREAD

**Issue by dbholmes** [theripper93/theripper93wiki#2]
not sure if this is the proper place to ask a question on Foundry V10 and Levels Latest version. but I have a  have a weird problem with a map I trying to complete. it has 4 levels and a roof ( I am using levels) I am placing some monsters in the basement level (-10, -1) I also have a test character in the basement as to test the look and feel of the lay out. the test character see the basement and nothing else it looks normal on both user and GM screens. i select a Monster on the GM screen and suddenly I see all the tiles from the other levels none that are directly above but all the others and the doors show up. I have a MP4 of me switching between the characters but didn't want to post it with out approval. any help would be appreciated.

**Comment by apriltaoyvr** [comment]
This is not the correct place to ask this question as the Issues subpages on Github are for addressing issues related to the repo itself (i.e. the docs page). Please view https://theripper93.com/info/troubleshooting.
